### ISSUE TITLE
Provide more details in the footer component

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/thenativeweb-ux#350]
### What is this feature about?

Right now, the footer shows just a copyright notice, and the `MadeBy` component. In addition to that, we need a few more things, which the user should be able to enable and configure separately. This includes:

- An option to edit the page on GitHub.
- A link to the imprint.
- A link to the privacy policy.

We should *not* provide the imprint and the privacy policy as components, at least not as part of the open-source UX package.

### What needs to be done to implement this feature?

- [x] Add an optional `editThisPageOnGitHub` property, which – if used – must be set to the url of the page
- [x] Add an optional `showImprint` property, which – if used – must be set to the url of the imprint.
- [x] Add an optional `showPrivacyPolicy` property, which – if used – must be set to the url of the privacy policy.
- [x] Adjust respectively add tests

**Comment by mattwagl** [comment]
Work has begun in this branch [feat-provide-more-details-in-footer](https://github.com/thenativeweb/thenativeweb-ux/tree/feat-provide-more-details-in-footer). Tests are still missing.
