### ISSUE TITLE
Add support for tabIndex on interactive components

### ISSUE THREAD

**Issue by dotKuro** [thenativeweb/thenativeweb-ux#729]
### What is this feature about?

An important accessibility feature is to be able to navigate a website comfortably only using the keyboard. This is usually done using the `Tab` key. By default all interactive elements will be focused in order of the preorder traversal of the HTML tree.

This might not be sensible for all situations, for example if you have a pop up menu that opens by focusing an element on the page, you may want to focus the pop up next instead of what ever element would be next according to the HTML tree. In situations like this the tabIndex can be used to manipulate the order of the tab navigation.

### What needs to be done to implement this feature?

- [x] Identify which components contain interactive elements (`<a>`,  `<button>`, etc.)
- [x] Expose the tabIndex of the inner elements on the component
- [ ] Add tabIndex support for remaining components

**Comment by dotKuro** [comment]
This mostly affects the components of the input type, but also components that provide links by default like the MadeBy or the Footer component.

**Comment by goloroden** [comment]
How many components is this in numbers?

**Comment by dotKuro** [comment]
The exact list is:
- Footer (contains Links)
- MadeBy (contains Links)
- Button
- CheckBox
- Dropdown
- Link
- Textarea
- Textbox

**Comment by goloroden** [comment]
Thanks for the update. This is TBH less than what I had expected, nevertheless I'd say let's only introduce it right where it's actually needed right now.

Thanks anyway 😊
